# Week11. Part 2: NumPy, Pandas

## India Trade data
- https://www.kaggle.com/lakshyaag/india-trade-data/




## NumPy
### Description
- Ref: https://numpy.org/doc/stable/
- Ref: https://jakevdp.github.io/PythonDataScienceHandbook/index.html
- Ref: https://docs.scipy.org/doc/numpy/user/whatisnumpy.html
- Ref: https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf
- NumPy provides a multidimensional array object.
- Each object comes with an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.
- Basically, you can use NumPy to create ndarray (N-dimensional array) and easily manipulate the array. It is super fast because it is written in C.
### How is it different from Python arrays?
- Python lists can be modified -- you can add and remove elements. NumPy arrays have a fixed size at creation.
- Python lists can contain different data types. NumPy arrays can only have one data type. If you put in mixed types, they become a string.
- NumPy arrays come prepackaged with advanced mathematical operations. The operations are super fast even on large numbers of data and they use less memory.
### Why use NumPy
- Most data analysis programs use NumPy to manipulate data. They might take in data as standard Python lists, but they convert it to a NumPy array and manipulate the data using NumPy routines and output the transformed data as a NumPy array.
- NumPy data array is the main data type used in most scientific and mathematical Python-based packages.
### Simple example


In [2]:
# Square a list using Python
squared_values = []
for number in range(10):
    squared_values.append(number*number)

print(squared_values)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [3]:
# Square a list using NumPy
import numpy as np

vector = np.array(range(10))
scalar = 5
print(vector * scalar)
print(vector * vector)

[ 0  5 10 15 20 25 30 35 40 45]
[ 0  1  4  9 16 25 36 49 64 81]


### Numpy Basics
- NumPy arrays can be a 1-D array, called a vector, or a 2-D array, called a matrix, or higher

#### NumPy casting -- covert Python list to a NumPy array

In [4]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [5]:
import numpy as np

my_vector = np.array(my_list)
my_vector

array([1, 2, 3])

In [6]:
my_matrix1 = np.array([my_list, my_list])
my_matrix1

array([[1, 2, 3],
       [1, 2, 3]])

In [7]:
my_matrix2 = np.hstack([my_list, my_list])
my_matrix2

array([1, 2, 3, 1, 2, 3])

In [8]:
my_matrix3 = np.vstack([my_list, my_list])
my_matrix3

array([[1, 2, 3],
       [1, 2, 3]])

In [9]:
my_nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_matrix4 = np.array(my_nested_list)
my_matrix4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
my_list1 = [[1,2], [3,4]]
my_list2 = [[5,6], [7,8]]
np.hstack([my_list1, my_list2])

In [ ]:
np.vstack([my_list1, my_list2])

#### NumPy dtype argument
- most of array creating function accept `dtype` argument
- `dtype` specify data-type of each element in the array
  - int, int32, uint32, int64, float, float32, float64, object

In [ ]:
my_vector = np.array([1, 2, 3], dtype='int')
my_vector.dtype

#### NumPy creating arrays

In [ ]:
my_list = range(10)
my_list

In [ ]:
## Create array using arange
my_vector = np.arange(10)
my_vector

In [ ]:
np.arange(0, 10)

In [ ]:
np.arange(0, 10, 2)

In [ ]:
## Create array of zeros
np.zeros(3)

In [ ]:
np.zeros((3,3))

In [ ]:
## Create array of ones
np.ones(3)

In [ ]:
np.ones((3,3))

In [ ]:
np.ones(3)*4

In [ ]:
np.full((3,3),4)

In [ ]:
## Create evenly spaced vector
### Example use case: when you have Y values for a plot but need to generate X values
### *** Includes both start an end
# np.arange(start, end(not included), step size)
# np.linspace(start, end(included), number_of_points)
np.linspace(0, 10, 5)

In [ ]:
np.linspace(1900, 2000, 11)

## Create an identify matrix

In [ ]:
np.eye(3)

## Creating an empty array

In [ ]:
np.empty((2,3))

## Creating Random Numbers
- Ref: https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html

In [ ]:
# Uniform distribution
np.random.rand(3)

In [ ]:
np.random.rand(3,3)

In [ ]:
# Normal distribution
np.random.randn(3)

In [ ]:
np.random.randn(3,3)

In [ ]:
# Random integers
# np.random.randint(start, end(not_included), size)
np.random.randint(1,101)

In [ ]:
np.random.randint(1,101,5)

## Reshaping arrays

In [ ]:
vector = np.arange(1,10)
vector

In [ ]:
print(vector.reshape(3,3))

In [ ]:
vector = np.arange(1,13)
print(vector.reshape(3,4))

## Basic array operations

In [ ]:
vector = np.random.randint(1,50,25)
vector

In [ ]:
# Min
vector.min()

In [ ]:
# Max
vector.max()

In [ ]:
# get location of min value
index = vector.argmin()
index

In [ ]:
# get location of max value
index = vector.argmax()
index

In [ ]:
# get shape
vector.shape

In [ ]:
my_matrix = vector.reshape(5, 5)
my_matrix.shape

## Indexing a 1-D array -- vector

In [ ]:
vector = np.array(range(10))
vector
# vector[index]
# vector [start:end]
# vector [:end]
# vector [start:]
# vector [start, end, step]

In [ ]:
# read
vector[3]

In [ ]:
vector[3:8]

In [ ]:
vector[:5]

In [ ]:
vector[5:]

In [ ]:
vector[3:9:2]

In [ ]:
vector[-1]

In [ ]:
# update
vector[3] = 33
vector

In [ ]:
vector[3:8] = 38
vector

In [ ]:
vector[:5] = 55
vector

In [ ]:
vector[5:] = 555
vector

In [ ]:
vector[3:9:2] = 392
vector

In [ ]:
vector[-1] = -1
vector

## Setting multiple values at once -- Broadcasting
- There are two main features of NumPy arrays
  - Broadcasting -- set multiple values at once
  - Vectorization -- no need for explicit looping -- example, vector multiplication or squaring


In [ ]:
vector[3:6] = 12


## Indexing a 2-D array -- Matrix
- Remember -- Python is zero-indexed

In [ ]:
matrix = np.array(range(1,10)).reshape((3,3))
matrix

In [ ]:
matrix[0,0]  # single [] with comma separated indices is preferred

In [ ]:
matrix[0][0]

In [ ]:
matrix[2,2]

In [ ]:
matrix[2][2]


In [ ]:
matrix[:,2]

In [ ]:
matrix[1,:]

In [ ]:
matrix[:2]

In [ ]:
matrix[:2,:]

In [ ]:
matrix[:,1:] # grab all the rows, but columns starting from 1

## BE CAREFUL! View vs Copy
- Many operations in numpy and pandas creates a view rather than a copy
  - view: refer to original data but in a different perspective
  - copy: completely new array with copied data
- If you store a slice of an array in a new variable, changes in the new variable will be reflected in the original array.

In [ ]:
vector = np.array(range(10))
vector

In [ ]:
my_slice = vector[3:7]
my_slice[:] = 20
my_slice

In [ ]:
print(vector)

- Copy the array if you need a copy

In [ ]:
vector = np.array(range(10))
vector

In [ ]:
my_slice_copy = vector[3:7].copy()
my_slice_copy[:] = 30
my_slice_copy

In [ ]:
vector

- similar with reshape

In [ ]:
vector = np.array(range(16))
vector

In [ ]:
matrix = vector.reshape((4,4))
matrix

In [ ]:
matrix[1:3,1:3] = 22
matrix

In [ ]:
vector

In [ ]:
submatrix = matrix[1:3,1:3]
submatrix

In [ ]:
submatrix[0:2,0:2] = 111*np.eye(2)
submatrix

In [ ]:
matrix

In [ ]:
vector

In [ ]:
# But
submatrix = 222*np.eye(2)
submatrix

In [ ]:
matrix

In [ ]:
vector

## Conditional selection

In [ ]:
vector = np.arange(10)
vector

In [ ]:
gt2 = vector > 2 # create boolean (condition)
gt2

In [ ]:
lt8 = vector < 8 # create boolean
gt2

In [ ]:
selected_gt2 = vector[gt2] # apply condition to select
selected_gt2

In [ ]:
selected_lt8 = vector[lt8] # apply condition to select
selected_lt8

In [ ]:
# no need to use variables
vector[vector>2]

In [ ]:
vector[vector<8]

In [ ]:
cond = (vector>2) & (vector<7)
vector[cond]

In [ ]:
cond = (vector>=2) & (vector<=7)
vector[cond]


### view or copy?

In [10]:
# view or copy?
vector = np.arange(10)
selected_lt8 = vector[vector < 8]
selected_lt8 = -11
print(selected_lt8)
print(vector)

-11
[0 1 2 3 4 5 6 7 8 9]


In [11]:
# How about now?
vector = np.arange(10)
selected_lt8 = vector[vector < 8]
selected_lt8[:] = -11
print(selected_lt8)
print(vector)

[-11 -11 -11 -11 -11 -11 -11 -11]
[0 1 2 3 4 5 6 7 8 9]


In [12]:
# What about now?
vector = np.arange(10)
vector[vector < 8] = -11
print(vector)

[-11 -11 -11 -11 -11 -11 -11 -11   8   9]


## Array operations -- Basic

In [ ]:
vector = np.arange(10)
vector

In [ ]:
vector + vector

In [ ]:
vector - vector

In [ ]:
vector * vector

In [ ]:
vector / vector # problem!!! return `nan`

In [ ]:
vector + 10

In [ ]:
vector - 10

In [ ]:
vector * 10

In [ ]:
vector / 10

## Array operations -- Advanced
- Ref: https://docs.scipy.org/doc/numpy/reference/ufuncs.html#math-operations
- https://stackoverflow.com/questions/25773245/ambiguity-in-pandas-dataframe-numpy-array-axis-definition/43413031

In [ ]:
vector = np.arange(10)
vector

In [ ]:
np.max(vector)

In [ ]:
np.min(vector)

In [ ]:
np.sqrt(vector)

In [ ]:
np.log(vector)

In [ ]:
sum(vector<5)

In [ ]:
import math
vector = np.arange(1,11) * math.pi
np.sin(vector)

In [ ]:
vector = np.arange(0,math.pi+math.pi/4,math.pi/4)
np.sin(vector)

In [ ]:
matrix = np.random.rand(5,5)
np.floor(matrix*1000)/1000

In [ ]:
np.round(matrix*1000)/1000

In [ ]:
np.ceil(matrix*1000)/1000

In [ ]:
matrix = np.arange(1,13).reshape(3,4)
matrix

In [ ]:
matrix.sum(axis=1)

In [ ]:
matrix.sum(axis=0)

In [ ]:
matrix.cumsum()

In [ ]:
matrix.cumprod()

In [ ]:
matrix.min(axis=1)

In [ ]:
matrix.min(axis=0)

In [ ]:
matrix.max(axis=1)

In [ ]:
matrix.max(axis=0)

In [ ]:
matrix = np.array([1,2,3]*3).reshape(3,3)
matrix

In [ ]:
np.unique(matrix)



# Pandas
- Built-on top of NumPy -- meaning the underlying data structure used is ndarray
- Pandas provides series which are like NumPy arrays but with associated index labels -- meaning are like column  labels
  or row labels. Element data type can be different
- Pandas also provides dataframes which are like Excel sheets or database tables

### Basic examples

In [ ]:
import numpy as np
import pandas as pd

header = ['chrom', 'pos', 'filter']
data = [4, 12345, 38.4]
vector = np.array(data)
print(vector)
s1 = pd.Series(data=data) # Notice the data type is float
s1

In [ ]:
s2 = pd.Series(data=data, index=header)
s2

In [ ]:
# can also do as positional arguments
s1 = pd.Series(data)
s1

In [ ]:
s2 = pd.Series(data, header)
s2

In [ ]:
# can use a dictionary to initialize a panda series
data_dict = {'chrom': 4, 'pos': 12345, 'filter': 38.4}
s3 = pd.Series(data_dict)
s3

In [ ]:
# can hold "different" data types (it all casted to python object type and is not efficient any more)
data = [1, '2s', 34]
pd.Series(data)


## Basic indexing

In [ ]:
## Using index labels to fetch element
header = ['chrom', 'pos', 'filter', 'qual']
data = [4, 12345, 38.4, 12.3]
series = pd.Series(data=data, index=header)
series

In [ ]:
series['chrom']

In [ ]:
series['filter']

In [ ]:
series['chrom':'filter']

In [ ]:
series.loc['chrom']

In [ ]:
series.loc['filter']

In [ ]:
series.loc['chrom':'filter']

In [ ]:
series.iloc[0]

In [ ]:
series.iloc[2]

In [ ]:
series.iloc[0:2]

In [ ]:
series[series>20]

In [ ]:
series[np.array((True,False,True,False))]

In [ ]:
# interger index
series = pd.Series(data)
series[0]

## Basic operations

In [ ]:
header1 = ['chrom', 'pos', 'filter']
data1 = [4, 12345, 38.4]
header2 = ['chrom', 'pos', 'filter', 'qual']
data2 = [3, 4899, 234, 89.9]

s1 = pd.Series(data1, header1)
s2 = pd.Series(data2, header2)
print(s1,"\n\n", s2)

In [ ]:
s1+s2

In [ ]:
header1 = ['chrom', 'pos', 'filter']
data1 = [4, 12345, 38.4]
header2 = ['chrom', 'pos', 'filter', 'qual']
data2 = ['3', 4899, 234, 89.9]

s1 = pd.Series(data1, header1)
s2 = pd.Series(data2, header2)
print(s1,"\n\n", s2)

In [ ]:
s1+s2

In [ ]:
data1 = [4, 12345, 38.4]
data2 = [3, 4899, 234, 89.9]

s1 = pd.Series(data1)
s2 = pd.Series(data2)
print(s1,"\n\n", s2)

In [ ]:
s1 + s2

In [ ]:
## IMPORTANT - with index labels -- operations are based on label
header1 = ['pos', 'filter', 'chrom']
data1 = [12345, 38.4, 4]
header2 = ['chrom', 'pos', 'filter', 'qual']
data2 = [3, 4899, 234, 89.9]

s1 = pd.Series(data1, header1)
s2 = pd.Series(data2, header2)
print(s1,"\n\n", s2)
s1+s2

## Dataframes --
- Dataframe is composed of series
- Ref: https://pandas.pydata.org/docs/reference/api/pandas.io.formats.style.Styler.html#pandas.io.formats.style.Styler

In [ ]:
import numpy as np
import pandas as pd

header = ['exam1', 'exam2', 'exam3']
data = np.random.randint(65, 101, 12).reshape(4,3)
students = ['student1', 'student2', 'student3', 'student4']

df = pd.DataFrame(data=data, columns=header)
df

In [ ]:
df = pd.DataFrame(data=data, index=students, columns=header)
df

In [ ]:
# referencing column
df['exam1']

In [ ]:
df.exam1 # not a good way to do this

In [ ]:
df['average'] = (df['exam1'] + df['exam2'] + df['exam3'])/3
df

In [ ]:
df.drop('average') # does not work because default for drop is to work on row labels

In [ ]:
df.drop('average', axis=1)# works on column labels

In [ ]:
## STILL NOT DROPPED from df
df

In [ ]:
df.drop('average', axis=1, inplace=True)
df

In [ ]:
## drop a student
df.drop('student3')

In [ ]:
df.drop('student3', inplace=True)
df

In [ ]:
header = ['exam1', 'exam2', 'exam3']
data = np.random.randint(65, 101, 12).reshape(4,3)
students = ['student1', 'student2', 'student3', 'student3']
df = pd.DataFrame(data=data, index=students, columns=header)
df

In [ ]:
df.drop('student3')

In [ ]:
df.drop('student3', inplace=True)
df

# (Row,Column) == (axis=0, axis=1) df.shape
# Matrix NxM - N-rows, M-cols; a(i,j) - i-row, j-column

In [ ]:
## Row is referred to as axis=0
## Column is referred to as axis=1
## (R,C) == (axis=0, axis=1) df.shape

## Select Dataframe rows

In [ ]:
header = ['exam1', 'exam2', 'exam3']
data = np.random.randint(65, 101, 12).reshape(4,3)
students = ['student1', 'student2', 'student3', 'student4']
df = pd.DataFrame(data=data, index=students, columns=header)
df

In [ ]:
df.loc['student1']

In [ ]:
df.iloc[0] ## remember that column names do not count as rows

In [ ]:
df.loc[['student1','student2']]

In [ ]:
df.iloc[[0,2]] ## rem

In [ ]:
df.loc[[True,False,True,False]]

In [ ]:
df.iloc[[True,False,True,False]] ##

## Select subset of data

In [ ]:
df.loc['student1', 'exam1']

In [ ]:
df.loc[['student1', 'student3'], ['exam1', 'exam3']]

In [ ]:
df.loc['student1':'student2', 'exam1':'exam2']

In [ ]:
df.iloc[0, 0]

In [ ]:
df.iloc[[0, 2], [0, 2]]

In [ ]:
df.iloc[0:3, 0:3]

## Use conditions to select

In [ ]:
header = ['exam1', 'exam2', 'exam3']
data = np.random.randint(65, 101, 12).reshape(4,3)
students = ['student1', 'student2', 'student3', 'student4']
df = pd.DataFrame(data=data, index=students, columns=header)
df

In [ ]:
df>=90

In [ ]:
df[df>=90]

In [ ]:
df['exam1']>=85 #

In [ ]:
df[df['exam1']>=85] # gives all columns where exam1 is greater than 85

In [ ]:
df[df['exam1']>=85]['exam3']

In [ ]:
df[df['exam1']>=85][['exam2', 'exam3']]

In [ ]:
df[(df['exam1']>=85) & (df['exam2']>=85)]

In [ ]:
df[(df['exam1']>=85) & (df['exam2']>=85)]['exam3']

In [ ]:
df[(df['exam1']>=85) | (df['exam2']>=85)]

In [ ]:
df[(df['exam1']>=85) | (df['exam2']>=85)]['exam3']

## Adding student index

In [ ]:
header = ['exam1', 'exam2', 'exam3']
data = np.random.randint(65, 101, 12).reshape(4,3)
students = ['student1', 'student2', 'student3', 'student4']
df = pd.DataFrame(data=data, columns=header)
df

In [ ]:
df['name'] = students
df

In [ ]:
df.set_index('name', inplace=True)
df

In [ ]:
df.loc['student1']

In [ ]:
df.reset_index(inplace=True)
df

## Multi-index data

In [ ]:
students = 'student1 student1 student1 student2 student2 student2 student3 student3 student3'
exams = 'exam1 exam2 exam3'.split()*3
classes = 'class1 class2'
index = list(zip(students.split(), exams))
index = pd.MultiIndex.from_tuples(index)
index

In [ ]:
df = pd.DataFrame(np.random.randint(65, 101, 3*3*2).reshape(9,2) , index, classes.split())
df

In [ ]:
df.loc['student1']

In [ ]:
df.loc['student1'].loc['exam1']['class1']

In [ ]:
df.index.names

In [ ]:
df.index.names = ['Students', 'Exams']

In [ ]:
df

In [ ]:
## cross-section
df.xs('student1')

In [ ]:
df.xs('exam1', level='Exams')

## Dealing with missing data


In [ ]:
my_dict = {'student1': [90, 84, np.nan], 'student2': [77, np.nan, np.nan], 'student3': [88, 65, 93]}
df = pd.DataFrame(my_dict)
df

In [ ]:
df.dropna()

In [ ]:
df.dropna(axis=0)

In [ ]:
df.dropna(axis=1)

In [ ]:
df.dropna(thresh=2)

In [ ]:
df.fillna(value=55)

In [ ]:
df.drop(axis=0, labels=[1,2])

In [ ]:
df.drop(axis=1, columns=['student1'])

## Groupby

In [ ]:
my_dict = {
    'Exams': 'exam1 exam1 exam1'.split() + 'exam2 exam2 exam2'.split() + 'exam3 exam3 exam3'.split(),
    'Students': 'student1 student2 student3'.split()*3,
    'Scores': np.random.randint(65,101,9)
}
df = pd.DataFrame(my_dict)
df

In [ ]:
df.groupby('Students').mean()

In [ ]:
df.groupby('Students').mean().loc['student1']

In [ ]:
df.groupby('Exams').max()['Scores']

In [ ]:
df.groupby('Exams').describe()

In [ ]:
df.groupby('Students').describe().transpose()

## Merging  -- SQL JOIN

In [ ]:
departments = {
    'DepartmentId': [1, 2, 3, 4],
    'DepartmentName': ['IT', 'Physics', 'Arts', 'Math']
}

df1 = pd.DataFrame(departments)
df1

In [ ]:
students = {
    'StudentId': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'StudentName': ['Michael', 'John', 'Jack', 'Sara', 'Sally', 'Jena', 'Nancy', 'Adam', 'Stevens', 'George'],
    'DepartmentId': [1, 1, 1, 2, 2, np.nan, 2, 3, 3, np.nan]
}

df2 = pd.DataFrame(students)
df2

In [ ]:
marks = {
    'MarkId': [1, 2, 3, 4, 5, 6, 7, 8],
    'StudentId': [1, 2, 3, 4, 5, 6, 7, 8],
    'Mark': [18, 20, 16, 19, 14, 20, 20, 20]
}

df3 = pd.DataFrame(marks)
df3

In [ ]:
pd.merge(df2, df1, how='inner', on='DepartmentId')

In [ ]:
pd.merge(df1, df2, how='inner', on='DepartmentId')

In [ ]:
pd.merge(df1, df2, how='outer', on='DepartmentId')

In [ ]:
pd.merge(df2, df1, how='right', on='DepartmentId')

In [ ]:
pd.merge(df3, pd.merge(df2, df1, how='inner', on='DepartmentId'), how='inner', on='StudentId')

In [ ]:
data = pd.merge(df3, pd.merge(df2, df1, how='inner', on='DepartmentId'), how='inner', on='StudentId')
data

In [ ]:
data[['StudentName', 'Mark', 'DepartmentName']]

- ref: https://stackoverflow.com/a/48411543

## Concatenation

In [ ]:
d1 = {
    'C0': ['COR0', 'COR1', 'COR2'],
    'C1': ['C1R0', 'C1R1', 'C2R2'],
    'C2': ['C2R0', 'C2R1', 'C2R2'],
}

df1 = pd.DataFrame(d1)
df1

In [ ]:
d2 = {
    'C0': ['C0R3', 'C0R4', 'C0R5'],
    'C1': ['C1R3', 'C1R4', 'C1R5'],
    'C2': ['C2R3', 'C2R4', 'C2R5'],
}

df2 = pd.DataFrame(d2)
df2

In [ ]:
d3 = {
    'C0': ['C0R6', 'C0R7', 'C0R8'],
    'C1': ['C1R6', 'C1R7', 'C1R8'],
    'C2': ['C2R6', 'C2R7', 'C2R8'],
}

df3 = pd.DataFrame(d3)
df3

In [ ]:
pd.concat([df1, df2, df3])

In [ ]:
## Concatenation -- Fix index

d1 = {
    'C0': ['COR0', 'COR1', 'COR2'],
    'C1': ['C1R0', 'C1R1', 'C2R2'],
    'C2': ['C2R0', 'C2R1', 'C2R2'],
}

df1 = pd.DataFrame(d1, index=[1, 2, 3])
df1

In [ ]:
d2 = {
    'C0': ['C0R3', 'C0R4', 'C0R5'],
    'C1': ['C1R3', 'C1R4', 'C1R5'],
    'C2': ['C2R3', 'C2R4', 'C2R5'],
}

df2 = pd.DataFrame(d2, index=[4, 5, 6])
df2

In [ ]:
d3 = {
    'C0': ['C0R6', 'C0R7', 'C0R8'],
    'C1': ['C1R6', 'C1R7', 'C1R8'],
    'C2': ['C2R6', 'C2R7', 'C2R8'],
}

df3 = pd.DataFrame(d3, index=[7, 8, 9])
df3

In [ ]:
pd.concat([df1, df2, df3])

## More Pandas Operations

In [ ]:
data['DepartmentName'].unique()

In [ ]:
data['DepartmentName'].nunique()

In [ ]:
data['DepartmentName'].value_counts()

In [ ]:
data[data['Mark']>17]

## Lambda with Pandas
- Scale marks by 5

In [ ]:
def times5(val):
    return val * 5

data['Mark'].apply(times5)

In [ ]:
data['Mark'].apply(lambda val: val*5)

- Upper all department names

In [ ]:
def upper(string):
    return string.upper()

data['DepartmentName'].apply(upper)

In [ ]:
data['DepartmentName'].apply(lambda string: string.upper())

In [ ]:
mapping = {18: 'B', 14: 'C', 19: 'A-', 20: 'A+'}
df3['Mark'].map(mapping)

## Dropping columns

In [ ]:
data.columns

In [ ]:
data.drop(['StudentId', 'MarkId' , 'DepartmentId'], axis=1)

## Sorting

In [ ]:
data.sort_values('Mark')

In [ ]:
data.sort_values('Mark', ascending=False)

## Importing CSV, TSV

In [ ]:
data = pd.read_csv('students.tsv', sep='\t', names=['lastname', 'firstname', 'username', 'exam1', 'exam2', 'exam3'])
data

In [ ]:
data.sort_values('exam1', ascending=False)

In [ ]:
data[['exam1', 'exam2', 'exam3']].mean()

In [ ]:
data['average']= np.mean(data[['exam1', 'exam2', 'exam3']], axis=1)

In [ ]:
data.sort_values('average', ascending=False)

In [ ]:
data.to_csv('output.tsv', sep='\t', index=False, header=False)

## Other methods

In [ ]:
data.head()

In [ ]:
data.head(2)

In [ ]:
data.tail

In [ ]:
data.tail(3)

In [ ]:
data.shape

In [ ]:
data.iloc[3]

In [ ]:
data.columns

In [ ]:
data.dtypes

In [ ]:
data.info()

In [ ]:
data.get_dtype_counts()

In [ ]:
data.describe()

## More data manipulation

In [ ]:
data[data['exam1'].between(75, 85)]

In [ ]:
data[data['exam1'].in([75, 85, 95])

In [ ]:
data[data['exam1'].isin([75, 85, 95])]

In [ ]:
data['exam1'].unique()

In [ ]:
data['exam1'].nunique()

In [ ]:
np.sort(data['exam1'].unique())

## Example 5 in pandas

